package com.forecaster.Utility;

public class GlobalVariables {

    public static final String SUCCESS = "SUCCESS";
    public static final String FAILURE ="FAILURE" ;
    public static String profilePic="profilePic";
    public static String status="status";
    public static String notificationStatus="notificationStatus";
    public static String totalPoints="totalPoints";
    public static String _id="_id";
    public static String name="name";
    public static String birthPlace="birthPlace";
    public static String email="email";
    public static String mobileNumber="mobileNumber";
    public static String dob="dob";
    public static String gender="gender";
    public static String maritalStatus="maritalStatus";
    public static String createdAt="createdAt";
    public static String updatedAt="updatedAt";
    public static String __v="__v";
    public static String google="google";
    public static String facebook="facebook";
    public static String device_type="Android";
    public static String countryCode="countryCode";
    public static String password="password";
    public static String deviceToken="deviceToken";
    public static String jwtToken="jwtToken";
    public static String language="language";
    public static String islogin="LOGIN";
    public static String profileSetup="profileSetup";
    public static String totalRating="totalRating";
    public static String avgRating="avgRating";
    public static String onlineStatus="onlineStatus";
    public static String responseTime="responseTime";
    public static String pendingQueue="pendingQueue";
    public static String username="username";
    public static String profileComplete="profileComplete";
    public static String bookingCount="bookingCount";
    public static String aboutUs="aboutUs";
    public static String accountHolderName="accountHolderName";
    public static String accountNumber="accountNumber";
    public static String pricePerQues="pricePerQues";
    public static String categoryName="categoryName";
    public static String bankName="bankName";
    public static String uploadedVideo="uploadedVideo";
    public static String forcaster_name="forcaster_name";
    public static String videouri="videouri";
    public static String invalidoken="Invalid Token";
    public static String touchid="touchid";
    public static String old_passcode="old_passcode";
    public static String roomId="roomId";
    public static String senderId="senderId";
    public static String receiverId="receiverId";
    public static String message="message";
    public static String messageType="messageType";
    public static String langCode="lang_code";

    public static String url="url";
}
